version: '2.4' # Better compatibility for DSM 6.2

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: '${APP_SLUG}-app'
    restart: always
    volumes:
      - .:/usr/src/app
      - ${STORAGE_PATH}:/usr/src/app/storage
      - /usr/src/app/node_modules
    ports:
      - '${PORT}:3333'
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - mysql
      - redis
    networks:
      - adonis-net

  mysql:
    image: mysql:8.0
    container_name: '${APP_SLUG}-mysql'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - adonis-net

  redis:
    image: redis:alpine
    container_name: '${APP_SLUG}-redis'
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - adonis-net

networks:
  adonis-net:
    driver: bridge

volumes:
  db_data:
